const CITIZEN_COMPLAINTS = [
  {
    id:'CMP-2026-101', title:'Street Light Not Working',
    description:'The street light near the main bus stop has been out for over a week. Very dark at night causing safety concerns for pedestrians.',
    category:'Electricity & Lighting', severity:'medium',
    location:'18, Oak Lane, Springfield', rawDate:'2026-03-12', date:'12 Mar 2026',
    status:'inprogress', upvotes:7, upvoted:false,
    officer:'Priya Nair', dept:'Electricity Dept.',
    officerPhone:'+91 98765 11111', officerEmail:'priya.nair@cityfix.gov.in',
    eta:'15 Mar 2026', progress:60,
    comments:[{author:'Priya Nair (Officer)',date:'13 Mar 2026',text:'Field team dispatched. Faulty bulb identified, replacement ordered.'}],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done',   date:'12 Mar 2026, 10:32 AM', desc:'Complaint received and ID assigned.',          note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'done',   date:'12 Mar 2026, 02:15 PM', desc:'Verified by civic officer.',                  note:''},
      {step:'Assigned',   icon:'fa-user-tie',            state:'done',   date:'13 Mar 2026, 09:00 AM', desc:'Assigned to Priya Nair, Electricity Dept.',   note:''},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'active', date:'13 Mar 2026, 11:45 AM', desc:'Field team dispatched to location.',           note:'Estimated fix: 15 Mar 2026'},
      {step:'Resolved',   icon:'fa-circle-check',        state:'pending',date:'—',                     desc:'Awaiting resolution confirmation.',            note:''},
      {step:'Closed',     icon:'fa-lock',                state:'pending',date:'—',                     desc:'Pending citizen confirmation.',               note:''},
    ]
  },
  {
    id:'CMP-2026-102', title:'Garbage Not Collected',
    description:'Garbage collection truck has not come for 5 days. Waste piling up causing bad smell and health concerns.',
    category:'Garbage & Sanitation', severity:'medium',
    location:'Gandhi Nagar, Block C, Greenfield', rawDate:'2026-03-10', date:'10 Mar 2026',
    status:'pending', upvotes:12, upvoted:false,
    officer:'—', dept:'Sanitation Dept.',
    officerPhone:null, officerEmail:null, eta:null, progress:0,
    comments:[],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done',   date:'10 Mar 2026, 08:20 AM', desc:'Complaint received.',                         note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'done',   date:'10 Mar 2026, 12:00 PM', desc:'Verified by civic officer.',                  note:''},
      {step:'Assigned',   icon:'fa-user-tie',            state:'active', date:'Pending',               desc:'Waiting to be assigned to an officer.',        note:'Expected: 14 Mar 2026'},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'pending',date:'—',                     desc:'Not yet started.',                            note:''},
      {step:'Resolved',   icon:'fa-circle-check',        state:'pending',date:'—',                     desc:'Awaiting resolution.',                        note:''},
      {step:'Closed',     icon:'fa-lock',                state:'pending',date:'—',                     desc:'Pending closure.',                            note:''},
    ]
  },
  {
    id:'CMP-2026-103', title:'Water Leakage on Main Road',
    description:'Underground water pipe burst near the park. Water flooding the road for 2 days creating a traffic hazard.',
    category:'Water & Sewage', severity:'critical',
    location:'Civil Lines, Near Park, Riverside', rawDate:'2026-03-05', date:'05 Mar 2026',
    status:'resolved', upvotes:24, upvoted:true, rated:false, canReopen:true,
    officer:'Rajan Kumar', dept:'Water Dept.',
    officerPhone:'+91 98765 22222', officerEmail:'rajan.k@cityfix.gov.in',
    eta:null, progress:100,
    comments:[
      {author:'Rajan Kumar (Officer)',date:'05 Mar 2026',text:'Emergency crew deployed. Pipe sealed within 4 hours.'},
      {author:'Jane Doe',date:'06 Mar 2026',text:'Issue resolved! Road cleared. Thank you for the quick response.'},
    ],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done', date:'05 Mar 2026, 07:10 AM', desc:'Complaint received.',                                note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'done', date:'05 Mar 2026, 09:30 AM', desc:'Marked critical. Urgent review initiated.',          note:''},
      {step:'Assigned',   icon:'fa-user-tie',            state:'done', date:'05 Mar 2026, 10:00 AM', desc:'Assigned to Rajan Kumar on priority basis.',         note:''},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'done', date:'05 Mar 2026, 12:30 PM', desc:'Emergency crew deployed. Pipe sealed.',              note:''},
      {step:'Resolved',   icon:'fa-circle-check',        state:'done', date:'06 Mar 2026, 04:00 PM', desc:'Issue fully resolved. Road cleared.',                note:''},
      {step:'Closed',     icon:'fa-lock',                state:'active',date:'Awaiting confirmation', desc:'Please confirm to close.',                          note:'Rate your experience'},
    ]
  },
  {
    id:'CMP-2026-104', title:'Water Leakage Near School',
    description:'Sewage water overflowing near the primary school entrance. Health hazard for children.',
    category:'Water & Sewage', severity:'high',
    location:'7, School Road, Springfield', rawDate:'2026-03-05', date:'05 Mar 2026',
    status:'pending', upvotes:9, upvoted:false,
    officer:'—', dept:'Water Dept.',
    officerPhone:null, officerEmail:null, eta:null, progress:0,
    comments:[],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done',   date:'05 Mar 2026, 09:45 AM', desc:'Complaint received.',                note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'active', date:'Under review',          desc:'Currently being reviewed.',          note:'Review in progress'},
      {step:'Assigned',   icon:'fa-user-tie',            state:'pending',date:'—',                     desc:'Pending assignment.',                note:''},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'pending',date:'—',                     desc:'Not yet started.',                   note:''},
      {step:'Resolved',   icon:'fa-circle-check',        state:'pending',date:'—',                     desc:'Awaiting resolution.',               note:''},
      {step:'Closed',     icon:'fa-lock',                state:'pending',date:'—',                     desc:'Pending closure.',                   note:''},
    ]
  },
  {
    id:'CMP-2026-105', title:'Water Leakage at Junction',
    description:'Pipe leaking at the main junction causing water wastage and slippery road conditions.',
    category:'Water & Sewage', severity:'medium',
    location:'MG Road Junction, Lakewood', rawDate:'2026-03-05', date:'05 Mar 2026',
    status:'inprogress', upvotes:5, upvoted:false,
    officer:'Suresh Pillai', dept:'Water Dept.',
    officerPhone:'+91 98765 33333', officerEmail:'suresh.p@cityfix.gov.in',
    eta:'17 Mar 2026', progress:35,
    comments:[],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done',   date:'05 Mar 2026',           desc:'Complaint received.',                note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'done',   date:'06 Mar 2026',           desc:'Verified.',                          note:''},
      {step:'Assigned',   icon:'fa-user-tie',            state:'done',   date:'07 Mar 2026',           desc:'Assigned to Suresh Pillai.',         note:''},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'active', date:'08 Mar 2026',           desc:'Repair work ongoing.',               note:'Est: 17 Mar 2026'},
      {step:'Resolved',   icon:'fa-circle-check',        state:'pending',date:'—',                     desc:'Awaiting resolution.',               note:''},
      {step:'Closed',     icon:'fa-lock',                state:'pending',date:'—',                     desc:'Pending closure.',                   note:''},
    ]
  },
  {
    id:'CMP-2026-106', title:'Garbage Not Collected – Sector 4',
    description:'Garbage bins overflowing in Sector 4. No collection done this week despite repeated complaints.',
    category:'Garbage & Sanitation', severity:'low',
    location:'Sector 4, Block B, Greenfield', rawDate:'2026-03-10', date:'10 Mar 2026',
    status:'resolved', upvotes:3, upvoted:false, rated:true, canReopen:false,
    officer:'Anita Sharma', dept:'Sanitation Dept.',
    officerPhone:'+91 98765 44444', officerEmail:'anita.s@cityfix.gov.in',
    eta:null, progress:100, rating:4,
    comments:[{author:'Anita Sharma (Officer)',date:'11 Mar 2026',text:'Collection done. Schedule updated to daily for this area.'}],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done', date:'10 Mar 2026', desc:'Complaint received.',  note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'done', date:'10 Mar 2026', desc:'Verified.',            note:''},
      {step:'Assigned',   icon:'fa-user-tie',            state:'done', date:'10 Mar 2026', desc:'Assigned to Anita.',   note:''},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'done', date:'11 Mar 2026', desc:'Collection started.',  note:''},
      {step:'Resolved',   icon:'fa-circle-check',        state:'done', date:'11 Mar 2026', desc:'Issue resolved.',      note:''},
      {step:'Closed',     icon:'fa-lock',                state:'active',date:'11 Mar 2026', desc:'Closed. Rated 4★.',   note:''},
    ]
  },
  {
    id:'CMP-2026-107', title:'Broken Road Near School',
    description:'Large potholes on the road leading to the school causing accidents and damage to vehicles.',
    category:'Roads & Potholes', severity:'high',
    location:'12, Station Road, Springfield', rawDate:'2026-03-08', date:'08 Mar 2026',
    status:'inprogress', upvotes:18, upvoted:false,
    officer:'Mohan Reddy', dept:'Roads Dept.',
    officerPhone:'+91 98765 55555', officerEmail:'mohan.r@cityfix.gov.in',
    eta:'20 Mar 2026', progress:25,
    comments:[],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done',   date:'08 Mar 2026', desc:'Complaint received.',     note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'done',   date:'08 Mar 2026', desc:'Verified, high priority.', note:''},
      {step:'Assigned',   icon:'fa-user-tie',            state:'done',   date:'09 Mar 2026', desc:'Assigned to Mohan Reddy.', note:''},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'active', date:'10 Mar 2026', desc:'Road repair in progress.',  note:'Est: 20 Mar 2026'},
      {step:'Resolved',   icon:'fa-circle-check',        state:'pending',date:'—',           desc:'Pending.',                 note:''},
      {step:'Closed',     icon:'fa-lock',                state:'pending',date:'—',           desc:'Pending.',                 note:''},
    ]
  },
  {
    id:'CMP-2026-108', title:'Noise Pollution at Night',
    description:'Nearby venue plays loud music past midnight every weekend. Disturbing entire neighbourhood.',
    category:'Noise Pollution', severity:'medium',
    location:'MG Road, Apt Block D, Riverside', rawDate:'2026-03-07', date:'07 Mar 2026',
    status:'pending', upvotes:31, upvoted:false,
    officer:'—', dept:'—',
    officerPhone:null, officerEmail:null, eta:null, progress:0,
    comments:[],
    timeline:[
      {step:'Submitted',  icon:'fa-paper-plane',        state:'done',   date:'07 Mar 2026', desc:'Complaint received.', note:''},
      {step:'Verified',   icon:'fa-shield-check',        state:'active', date:'Under review', desc:'Review in progress.', note:''},
      {step:'Assigned',   icon:'fa-user-tie',            state:'pending',date:'—',           desc:'Pending.',            note:''},
      {step:'In Progress',icon:'fa-screwdriver-wrench',  state:'pending',date:'—',           desc:'Not started.',        note:''},
      {step:'Resolved',   icon:'fa-circle-check',        state:'pending',date:'—',           desc:'Pending.',            note:''},
      {step:'Closed',     icon:'fa-lock',                state:'pending',date:'—',           desc:'Pending.',            note:''},
    ]
  },
];
